globalThis.WORDS_DATA = [
  { zh: "掉钥匙", pinyin: "diào yàoshi", viet: "làm rơi chìa khóa" },

  { zh: "当警察", pinyin: "dāng jǐngchá", viet: "làm cảnh sát" },
  { zh: "找律师", pinyin: "zhǎo lǜshī", viet: "tìm luật sư" },
  { zh: "读博士", pinyin: "dú bóshì", viet: "học tiến sĩ" },

  { zh: "做计划", pinyin: "zuò jìhuà", viet: "lập kế hoạch" },
  { zh: "听消息", pinyin: "tīng xiāoxi", viet: "nghe tin tức" },
  { zh: "找原因", pinyin: "zhǎo yuányīn", viet: "tìm nguyên nhân" },
  { zh: "看结果", pinyin: "kàn jiéguǒ", viet: "xem kết quả" },
  { zh: "用方法", pinyin: "yòng fāngfǎ", viet: "dùng phương pháp" },
  { zh: "完成任务", pinyin: "wánchéng rènwù", viet: "hoàn thành nhiệm vụ" },

  { zh: "很安全", pinyin: "hěn ānquán", viet: "rất an toàn" },
  { zh: "很危险", pinyin: "hěn wēixiǎn", viet: "rất nguy hiểm" },

  { zh: "去约会", pinyin: "qù yuēhuì", viet: "đi hẹn hò" },

  { zh: "一部分工作", pinyin: "yí bùfen gōngzuò", viet: "một phần công việc" },

  { zh: "丢手机", pinyin: "diū shǒujī", viet: "mất điện thoại" },

  { zh: "犯错误", pinyin: "fàn cuòwù", viet: "mắc sai lầm" },
  { zh: "支持你", pinyin: "zhīchí nǐ", viet: "ủng hộ bạn" },
  { zh: "给建议", pinyin: "gěi jiànyì", viet: "đưa ra lời khuyên" },
  { zh: "安排时间", pinyin: "ānpái shíjiān", viet: "sắp xếp thời gian" },

  { zh: "拿钥匙", pinyin: "ná yàoshi", viet: "cầm chìa khóa" },
  { zh: "看信息", pinyin: "kàn xìnxī", viet: "xem thông tin" },
  { zh: "全部完成", pinyin: "quánbù wánchéng", viet: "hoàn thành toàn bộ" },
  { zh: "首先做", pinyin: "shǒuxiān zuò", viet: "làm trước tiên" },

  { zh: "交作业", pinyin: "jiāo zuòyè", viet: "nộp bài" },
  { zh: "坚持学习", pinyin: "jiānchí xuéxí", viet: "kiên trì học" },
  { zh: "目前情况", pinyin: "mùqián qíngkuàng", viet: "tình hình hiện tại" },
  { zh: "打电话给他", pinyin: "dǎ diànhuà gěi tā", viet: "gọi điện cho anh ấy" },
  { zh: "打算换工作", pinyin: "dǎsuàn huàn gōngzuò", viet: "dự định đổi công việc" },
  { zh: "告诉我", pinyin: "gàosù wǒ", viet: "nói cho tôi" },
  { zh: "排队买票", pinyin: "páiduì mǎi piào", viet: "xếp hàng mua vé" },
  { zh: "排除风险", pinyin: "páichú fēngxiǎn", viet: "loại bỏ rủi ro" },
  { zh: "支持工作", pinyin: "zhīchí gōngzuò", viet: "hỗ trợ công việc" },
  { zh: "优点很多", pinyin: "yōudiǎn hěn duō", viet: "có nhiều ưu điểm" },
  { zh: "价格优惠", pinyin: "jiàgé yōuhuì", viet: "giá ưu đãi" },
  { zh: "很大变化", pinyin: "hěn dà biànhuà", viet: "thay đổi lớn" },

  { zh: "提供信息", pinyin: "tígōng xìnxī", viet: "cung cấp thông tin" },
  { zh: "推广产品", pinyin: "tuīguǎng chǎnpǐn", viet: "quảng bá sản phẩm" },
  { zh: "失去工作", pinyin: "shīqù gōngzuò", viet: "mất việc" },
  { zh: "失去机会", pinyin: "shīqù jīhuì", viet: "mất cơ hội" },
  { zh: "工作原理", pinyin: "gōngzuò yuánlǐ", viet: "nguyên lý hoạt động" },
  { zh: "因为下雨", pinyin: "yīnwèi xiàyǔ", viet: "vì trời mưa" },

  { zh: "做生意", pinyin: "zuò shēngyi", viet: "kinh doanh" },
  { zh: "骗别人", pinyin: "piàn biérén", viet: "lừa người khác" },

  { zh: "很乱", pinyin: "hěn luàn", viet: "rất lộn xộn" },

  { zh: "满了", pinyin: "mǎn le", viet: "đầy rồi" },
  { zh: "打扰你", pinyin: "dǎrǎo nǐ", viet: "làm phiền bạn" },

  { zh: "收钱", pinyin: "shōu qián", viet: "nhận tiền" },
  { zh: "一秒钟", pinyin: "yì miǎo zhōng", viet: "1 giây" },
  { zh: "同时做", pinyin: "tóngshí zuò", viet: "làm đồng thời" },
  { zh: "项目完成", pinyin: "xiàngmù wánchéng", viet: "hoàn thành dự án" },
  { zh: "打出租车", pinyin: "dǎ chūzūchē", viet: "bắt taxi" },

  { zh: "输比赛", pinyin: "shū bǐsài", viet: "thua trận" },
  { zh: "电话号码", pinyin: "diànhuà hàomǎ", viet: "số điện thoại" },

  { zh: "法律问题", pinyin: "fǎlǜ wèntí", viet: "vấn đề pháp luật" },
  { zh: "使用手机", pinyin: "shǐyòng shǒujī", viet: "sử dụng điện thoại" },
  { zh: "看地图", pinyin: "kàn dìtú", viet: "xem bản đồ" },
  { zh: "参观公司", pinyin: "cānguān gōngsī", viet: "tham quan công ty" },
  { zh: "不同观点", pinyin: "bùtóng guāndiǎn", viet: "quan điểm khác nhau" },
  { zh: "晚上加班", pinyin: "wǎnshang jiābān", viet: "tăng ca buổi tối" },
  { zh: "增加收入", pinyin: "zēngjiā shōurù", viet: "tăng thu nhập" },
  { zh: "增加产量", pinyin: "zēngjiā chǎnliàng", viet: "tăng sản lượng" },
  { zh: "讨论问题", pinyin: "tǎolùn wèntí", viet: "thảo luận vấn đề" },
  { zh: "提高技巧", pinyin: "tígāo jìqiǎo", viet: "nâng cao kỹ năng" },
  { zh: "社区服务", pinyin: "shèqū fúwù", viet: "dịch vụ cộng đồng" },
  { zh: "说明原因", pinyin: "shuōmíng yuányīn", viet: "giải thích nguyên nhân" },

  { zh: "怀疑他", pinyin: "huáiyí tā", viet: "nghi ngờ anh ấy" },
  { zh: "拒绝他", pinyin: "jùjué tā", viet: "từ chối anh ấy" },

  { zh: "找答案", pinyin: "zhǎo dáàn", viet: "tìm đáp án" },
  { zh: "参加活动", pinyin: "cānjiā huódòng", viet: "tham gia hoạt động" },
  { zh: "收到通知", pinyin: "shōudào tōngzhī", viet: "nhận thông báo" },

  { zh: "给意见", pinyin: "gěi yìjiàn", viet: "đưa ý kiến" },

  { zh: "浪费时间", pinyin: "làngfèi shíjiān", viet: "lãng phí thời gian" },
  { zh: "失败了", pinyin: "shībài le", viet: "thất bại rồi" },

  { zh: "很多观众", pinyin: "hěn duō guānzhòng", viet: "nhiều khán giả" },
  { zh: "反对这个", pinyin: "fǎnduì zhège", viet: "phản đối cái này" },

  { zh: "广告很多", pinyin: "guǎnggào hěn duō", viet: "nhiều quảng cáo" },

  { zh: "技术很好", pinyin: "jìshù hěn hǎo", viet: "kỹ thuật tốt" },
  { zh: "去旅行", pinyin: "qù lǚxíng", viet: "đi du lịch" },
  { zh: "找工作", pinyin: "zhǎo gōngzuò", viet: "tìm việc" },

  { zh: "家庭地址", pinyin: "jiātíng dìzhǐ", viet: "địa chỉ nhà" },

  { zh: "赚钱", pinyin: "zhuàn qián", viet: "kiếm tiền" },
  { zh: "收拾房间", pinyin: "shōushi fángjiān", viet: "dọn phòng" },
  { zh: "尊重别人", pinyin: "zūnzhòng biérén", viet: "tôn trọng người khác" },
  { zh: "回答问题", pinyin: "huídá wèntí", viet: "trả lời câu hỏi" },
  { zh: "答应请求", pinyin: "dāying qǐngqiú", viet: "đồng ý yêu cầu" },
  { zh: "答应请求", pinyin: "dāying qǐngqiú", viet: "đồng ý yêu cầu" },
  { zh: "优化方案", pinyin: "yōuhuà fāng'àn", viet: "tối ưu phương án" },
  { zh: "目的是什么", pinyin: "mùdì shì shénme", viet: "mục đích là gì" },

  { zh: "剩一点", pinyin: "shèng yìdiǎn", viet: "còn lại một ít" },
  { zh: "社会问题", pinyin: "shèhuì wèntí", viet: "vấn đề xã hội" },

  { zh: "好处很多", pinyin: "hǎochù hěn duō", viet: "nhiều lợi ích" },

  { zh: "出生在", pinyin: "chūshēng zài", viet: "sinh ra ở" },
  { zh: "估计一下", pinyin: "gūjì yíxià", viet: "ước tính một chút" },

  { zh: "这个地点", pinyin: "zhège dìdiǎn", viet: "địa điểm này" },
  { zh: "去大使馆", pinyin: "qù dàshǐguǎn", viet: "đi đại sứ quán" },
  { zh: "促使经济发展", pinyin: "cùshǐ jīngjì fāzhǎn", viet: "thúc đẩy phát triển kinh tế" },
  { zh: "致使项目失败", pinyin: "zhìshǐ xiàngmù shībài", viet: "dẫn đến dự án thất bại" },
  { zh: "很著名", pinyin: "hěn zhùmíng", viet: "rất nổi tiếng" },
  { zh: "免费使用", pinyin: "miǎnfèi shǐyòng", viet: "dùng miễn phí" },
  { zh: "很伤心", pinyin: "hěn shāngxīn", viet: "rất buồn" },
  { zh: "记者采访", pinyin: "jìzhě cǎifǎng", viet: "phóng viên phỏng vấn" },
  { zh: "仔细检查", pinyin: "zǐxì jiǎnchá", viet: "kiểm tra kỹ" },
  { zh: "很辣", pinyin: "hěn là", viet: "rất cay" },
  { zh: "去厕所", pinyin: "qù cèsuǒ", viet: "đi nhà vệ sinh" },
  { zh: "申请工作", pinyin: "shēnqǐng gōngzuò", viet: "xin việc" },
  { zh: "发展很快", pinyin: "fāzhǎn hěn kuài", viet: "phát triển rất nhanh" },
  { zh: "大学毕业", pinyin: "dàxué bìyè", viet: "tốt nghiệp đại học" },
  { zh: "正式开始", pinyin: "zhèngshì kāishǐ", viet: "chính thức bắt đầu" },
  { zh: "厨房里面", pinyin: "chúfáng lǐmiàn", viet: "bên trong nhà bếp" },
  { zh: "我的专业", pinyin: "wǒ de zhuānyè", viet: "chuyên ngành của tôi" },
  { zh: "没有条件", pinyin: "méiyǒu tiáojiàn", viet: "không có điều kiện" },
  { zh: "有点困", pinyin: "yǒudiǎn kùn", viet: "hơi buồn ngủ" },
  { zh: "输入密码", pinyin: "shūrù mìmǎ", viet: "nhập mật khẩu" },
  { zh: "工作经验", pinyin: "gōngzuò jīngyàn", viet: "kinh nghiệm làm việc" },
  { zh: "我的看法", pinyin: "wǒ de kànfǎ", viet: "quan điểm của tôi" },
  { zh: "很脏", pinyin: "hěn zāng", viet: "rất bẩn" },
  { zh: "提高速度", pinyin: "tígāo sùdù", viet: "tăng tốc độ" },
  { zh: "手机数字", pinyin: "shǒujī shùzì", viet: "chữ số trên điện thoại" },
  { zh: "暂时不用", pinyin: "zànshí bùyòng", viet: "tạm thời không dùng" },
  { zh: "科学研究", pinyin: "kēxué yánjiū", viet: "nghiên cứu khoa học" },
  { zh: "去餐厅", pinyin: "qù cāntīng", viet: "đi nhà hàng" },
  { zh: "距离很远", pinyin: "jùlí hěn yuǎn", viet: "khoảng cách rất xa" },
  { zh: "空气很好", pinyin: "kōngqì hěn hǎo", viet: "không khí rất tốt" },
  { zh: "护士工作", pinyin: "hùshi gōngzuò", viet: "công việc y tá" },
  { zh: "文章内容", pinyin: "wénzhāng nèiróng", viet: "nội dung bài viết" },
  { zh: "公司规定", pinyin: "gōngsī guīdìng", viet: "quy định công ty" },
  { zh: "效果很好", pinyin: "xiàoguǒ hěn hǎo", viet: "hiệu quả rất tốt" },
  { zh: "付现金", pinyin: "fù xiànjīn", viet: "trả tiền mặt" },
  { zh: "租房子", pinyin: "zū fángzi", viet: "thuê nhà" },
  { zh: "很自信", pinyin: "hěn zìxìn", viet: "rất tự tin" },
  { zh: "很轻", pinyin: "hěn qīng", viet: "rất nhẹ" },
  { zh: "很熟悉", pinyin: "hěn shúxi", viet: "rất quen" },
  { zh: "按照规定", pinyin: "ànzhào guīdìng", viet: "theo quy định" },
  { zh: "这个世纪", pinyin: "zhège shìjì", viet: "thế kỷ này" },
  { zh: "教育问题", pinyin: "jiàoyù wèntí", viet: "vấn đề giáo dục" },

  { zh: "管理公司", pinyin: "guǎnlǐ gōngsī", viet: "quản lý công ty" },
  { zh: "产生误会", pinyin: "chǎnshēng wùhuì", viet: "nảy sinh hiểu lầm" },
  { zh: "过桥", pinyin: "guò qiáo", viet: "đi qua cầu" },
  { zh: "举行活动", pinyin: "jǔxíng huódòng", viet: "tổ chức hoạt động" },
  { zh: "国际新闻", pinyin: "guójì xīnwén", viet: "tin quốc tế" },
  { zh: "竞争很大", pinyin: "jìngzhēng hěn dà", viet: "cạnh tranh rất lớn" },
  { zh: "顾客很多", pinyin: "gùkè hěn duō", viet: "nhiều khách hàng" },
  { zh: "交流经验", pinyin: "jiāoliú jīngyàn", viet: "trao đổi kinh nghiệm" },
  { zh: "我的年龄", pinyin: "wǒ de niánlíng", viet: "tuổi của tôi" },
  { zh: "符合要求", pinyin: "fúhé yāoqiú", viet: "phù hợp yêu cầu" },
  { zh: "交通方便", pinyin: "jiāotōng fāngbiàn", viet: "giao thông thuận tiện" },
  { zh: "适应生活", pinyin: "shìyìng shēnghuó", viet: "thích nghi cuộc sống" },
  { zh: "将来打算", pinyin: "jiānglái dǎsuan", viet: "dự định tương lai" },
  { zh: "坐沙发", pinyin: "zuò shāfā", viet: "ngồi ghế sofa" },
  { zh: "禁止吸烟", pinyin: "jìnzhǐ xīyān", viet: "cấm hút thuốc" },
  { zh: "经济发展", pinyin: "jīngjì fāzhǎn", viet: "phát triển kinh tế" },
  { zh: "去购物", pinyin: "qù gòuwù", viet: "đi mua sắm" },
  { zh: "抽烟的人", pinyin: "chōuyān de rén", viet: "người hút thuốc" },
  { zh: "航班延误", pinyin: "hángbān yánwù", viet: "chuyến bay bị trễ" },
  { zh: "胳膊疼", pinyin: "gēbo téng", viet: "đau cánh tay" },
  { zh: "整理房间", pinyin: "zhěnglǐ fángjiān", viet: "dọn phòng" },
  { zh: "森林里面", pinyin: "sēnlín lǐmiàn", viet: "bên trong rừng" },
  { zh: "打开网站", pinyin: "dǎkāi wǎngzhàn", viet: "mở website" },
  { zh: "商量一下", pinyin: "shāngliang yíxià", viet: "bàn một chút" },

  { zh: "准备材料", pinyin: "zhǔnbèi cáiliào", viet: "chuẩn bị tài liệu" },
  { zh: "练习对话", pinyin: "liànxí duìhuà", viet: "luyện hội thoại" },
  { zh: "写日记", pinyin: "xiě rìjì", viet: "viết nhật ký" },
  { zh: "大夫检查", pinyin: "dàifu jiǎnchá", viet: "bác sĩ kiểm tra" },
  { zh: "对面那家", pinyin: "duìmiàn nà jiā", viet: "cái ở đối diện" },
  { zh: "及时回复", pinyin: "jíshí huífù", viet: "trả lời kịp thời" },
  { zh: "迷路了", pinyin: "mílù le", viet: "bị lạc đường rồi" },
  { zh: "我的工资", pinyin: "wǒ de gōngzī", viet: "lương của tôi" },
  { zh: "基础知识", pinyin: "jīchǔ zhīshi", viet: "kiến thức cơ bản" },
  { zh: "准时到", pinyin: "zhǔnshí dào", viet: "đến đúng giờ" },
  { zh: "入口在那边", pinyin: "rùkǒu zài nàbian", viet: "lối vào ở bên kia" },
  { zh: "修理电脑", pinyin: "xiūlǐ diànnǎo", viet: "sửa máy tính" },
  { zh: "亲戚朋友", pinyin: "qīnqi péngyou", viet: "họ hàng bạn bè" },

  { zh: "喝果汁", pinyin: "hē guǒzhī", viet: "uống nước ép" },
  { zh: "小说作者", pinyin: "xiǎoshuō zuòzhě", viet: "tác giả tiểu thuyết" },
  { zh: "海洋环境", pinyin: "hǎiyáng huánjìng", viet: "môi trường biển" },
  { zh: "排队买票", pinyin: "páiduì mǎi piào", viet: "xếp hàng mua vé" },
  { zh: "放盐", pinyin: "fàng yán", viet: "cho muối" },
  { zh: "温度很高", pinyin: "wēndù hěn gāo", viet: "nhiệt độ rất cao" },
  { zh: "产品数量", pinyin: "chǎnpǐn shùliàng", viet: "số lượng sản phẩm" },
  { zh: "师傅你好", pinyin: "shīfu nǐ hǎo", viet: "chào bác/thầy" },
  { zh: "空气污染", pinyin: "kōngqì wūrǎn", viet: "ô nhiễm không khí" },
  { zh: "减肥成功", pinyin: "jiǎnféi chénggōng", viet: "giảm cân thành công" },
  { zh: "客厅里面", pinyin: "kètīng lǐmiàn", viet: "bên trong phòng khách" },
  { zh: "天上的云", pinyin: "tiān shang de yún", viet: "mây trên trời" },
  { zh: "这个学期", pinyin: "zhège xuéqī", viet: "học kỳ này" },
  { zh: "去卫生间", pinyin: "qù wèishēngjiān", viet: "đi nhà vệ sinh" },
  { zh: "阅读文章", pinyin: "yuèdú wénzhāng", viet: "đọc bài viết" },
  { zh: "加油站旁边", pinyin: "jiāyóuzhàn pángbiān", viet: "bên cạnh trạm xăng" },
  { zh: "中国首都", pinyin: "Zhōngguó shǒudū", viet: "thủ đô Trung Quốc" },

  { zh: "很暖和", pinyin: "hěn nuǎnhuo", viet: "rất ấm" },
  { zh: "很懒", pinyin: "hěn lǎn", viet: "rất lười" },
  { zh: "出差回来", pinyin: "chūchāi huílái", viet: "đi công tác về" },
  { zh: "垃圾桶里", pinyin: "lājītǒng lǐ", viet: "trong thùng rác" },
  { zh: "晚上加班", pinyin: "wǎnshang jiābān", viet: "tăng ca buổi tối" },
  { zh: "房东电话", pinyin: "fángdōng diànhuà", viet: "số điện thoại chủ nhà" },
  { zh: "高速公路上", pinyin: "gāosùgōnglù shàng", viet: "trên đường cao tốc" },
  { zh: "报名参加", pinyin: "bàomíng cānjiā", viet: "đăng ký tham gia" },
  { zh: "互联网时代", pinyin: "hùliánwǎng shídài", viet: "thời đại internet" },
  { zh: "去大使馆", pinyin: "qù dàshǐguǎn", viet: "đi đại sứ quán" },
  { zh: "申请签证", pinyin: "shēnqǐng qiānzhèng", viet: "xin visa" },
  { zh: "气候变化", pinyin: "qìhòu biànhuà", viet: "biến đổi khí hậu" },
  { zh: "手机付款", pinyin: "shǒujī fùkuǎn", viet: "thanh toán bằng điện thoại" },
  { zh: "去理发", pinyin: "qù lǐfà", viet: "đi cắt tóc" },
  { zh: "复印材料", pinyin: "fùyìn cáiliào", viet: "photo tài liệu" },
  { zh: "堵车了", pinyin: "dǔchē le", viet: "kẹt xe rồi" },
  { zh: "打折商品", pinyin: "dǎzhé shāngpǐn", viet: "hàng giảm giá" },
  { zh: "塑料袋子", pinyin: "sùliàodàizi", viet: "túi nilon" },
  { zh: "买西红柿", pinyin: "mǎi xīhóngshì", viet: "mua cà chua" },
  { zh: "招聘员工", pinyin: "zhāopìn yuángōng", viet: "tuyển nhân viên" },
  { zh: "读硕士", pinyin: "dú shuòshì", viet: "học thạc sĩ" },

  { zh: "学语法", pinyin: "xué yǔfǎ", viet: "học ngữ pháp" },
  { zh: "礼拜天见", pinyin: "lǐbàitiān jiàn", viet: "gặp vào chủ nhật" },
  { zh: "我的国籍", pinyin: "wǒ de guójí", viet: "quốc tịch của tôi" },
  { zh: "售货员服务", pinyin: "shòuhuòyuán fúwù", viet: "nhân viên bán hàng phục vụ" },
  { zh: "说普通话", pinyin: "shuō pǔtōnghuà", viet: "nói tiếng phổ thông" },
  { zh: "吃包子", pinyin: "chī bāozi", viet: "ăn bánh bao" },
  { zh: "打羽毛球", pinyin: "dǎ yǔmáoqiú", viet: "chơi cầu lông" },
  { zh: "吃烤鸭", pinyin: "chī kǎoyā", viet: "ăn vịt quay" },
  { zh: "预习课文", pinyin: "yùxí kèwén", viet: "chuẩn bị bài" },
  { zh: "发短信", pinyin: "fā duǎnxìn", viet: "gửi tin nhắn" },
  { zh: "翻译中文", pinyin: "fānyì zhōngwén", viet: "dịch tiếng Trung" },
];
