// Phân tích từng từ trong câu ví dụ
const wordAnalysis = {
  '家': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '每天', pinyin: 'měitiān', viet: 'mỗi ngày' },
    { zh: '下班', pinyin: 'xiàbān', viet: 'tan làm' },
    { zh: '以后', pinyin: 'yǐhòu', viet: 'sau khi' },
    { zh: '都', pinyin: 'dōu', viet: 'đều' },
    { zh: '回家', pinyin: 'huí jiā', viet: 'về nhà' },
    { zh: '吃饭', pinyin: 'chīfàn', viet: 'ăn cơm' },
  ],
  '房子': [
    { zh: '他们', pinyin: 'tāmen', viet: 'họ' },
    { zh: '家的', pinyin: 'jiā de', viet: 'của nhà' },
    { zh: '房子', pinyin: 'fángzi', viet: 'căn nhà' },
    { zh: '很大', pinyin: 'hěn dà', viet: 'rất lớn' },
    { zh: '有', pinyin: 'yǒu', viet: 'có' },
    { zh: '三个', pinyin: 'sān gè', viet: 'ba cái' },
    { zh: '房间', pinyin: 'fángjiān', viet: 'phòng ngủ' },
  ],
  '桌子': [
    { zh: '请', pinyin: 'qǐng', viet: 'vui lòng' },
    { zh: '把', pinyin: 'bǎ', viet: '(giới từ chỉ đối tượng)' },
    { zh: '那本书', pinyin: 'nà běn shū', viet: 'quyển sách đó' },
    { zh: '放在', pinyin: 'fàng zài', viet: 'đặt ở' },
    { zh: '桌子', pinyin: 'zhuōzi', viet: 'cái bàn' },
    { zh: '上面', pinyin: 'shàngmiàn', viet: 'phía trên' },
  ],
  '椅子': [
    { zh: '教室里', pinyin: 'jiàoshì lǐ', viet: 'trong lớp học' },
    { zh: '有', pinyin: 'yǒu', viet: 'có' },
    { zh: '很多', pinyin: 'hěn duō', viet: 'rất nhiều' },
    { zh: '椅子', pinyin: 'yǐzi', viet: 'ghế' },
    { zh: '学生们', pinyin: 'xuéshengmen', viet: 'các học sinh' },
    { zh: '都', pinyin: 'dōu', viet: 'đều' },
    { zh: '坐下了', pinyin: 'zuò xià le', viet: 'đã ngồi xuống' },
  ],
  '床': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '昨晚', pinyin: 'zuówǎn', viet: 'tối qua' },
    { zh: '太', pinyin: 'tài', viet: 'quá' },
    { zh: '累了', pinyin: 'lèi le', viet: 'mệt rồi' },
    { zh: '一躺到', pinyin: 'yī tǎng dào', viet: 'vừa nằm xuống' },
    { zh: '床上', pinyin: 'chuáng shàng', viet: 'trên giường' },
    { zh: '就', pinyin: 'jiù', viet: 'liền' },
    { zh: '睡着了', pinyin: 'shuìzháo le', viet: 'ngủ luôn' },
  ],
  '门': [
    { zh: '请', pinyin: 'qǐng', viet: 'vui lòng' },
    { zh: '关好', pinyin: 'guān hǎo', viet: 'đóng kỹ' },
    { zh: '门', pinyin: 'mén', viet: 'cửa' },
    { zh: '再走', pinyin: 'zài zǒu', viet: 'rồi hãy đi' },
    { zh: '外面', pinyin: 'wàimiàn', viet: 'bên ngoài' },
    { zh: '风', pinyin: 'fēng', viet: 'gió' },
    { zh: '很大', pinyin: 'hěn dà', viet: 'rất to' },
  ],
  '窗户': [
    { zh: '天气', pinyin: 'tiānqì', viet: 'thời tiết' },
    { zh: '很好', pinyin: 'hěn hǎo', viet: 'rất tốt' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '打开', pinyin: 'dǎkāi', viet: 'mở' },
    { zh: '窗户', pinyin: 'chuānghu', viet: 'cửa sổ' },
    { zh: '让', pinyin: 'ràng', viet: 'để cho' },
    { zh: '新鲜空气', pinyin: 'xīnxiān kōngqì', viet: 'không khí trong lành' },
    { zh: '进来', pinyin: 'jìnlái', viet: 'vào trong' },
  ],
  '电视': [
    { zh: '爸爸', pinyin: 'bàba', viet: 'bố' },
    { zh: '每天', pinyin: 'měitiān', viet: 'mỗi ngày' },
    { zh: '晚上', pinyin: 'wǎnshàng', viet: 'buổi tối' },
    { zh: '都', pinyin: 'dōu', viet: 'đều' },
    { zh: '喜欢', pinyin: 'xǐhuān', viet: 'thích' },
    { zh: '看', pinyin: 'kàn', viet: 'xem' },
    { zh: '电视新闻', pinyin: 'diànshì xīnwén', viet: 'tin tức trên tivi' },
  ],
  '手机': [
    { zh: '我的', pinyin: 'wǒ de', viet: 'của tôi' },
    { zh: '手机', pinyin: 'shǒujī', viet: 'điện thoại' },
    { zh: '没电了', pinyin: 'méidiàn le', viet: 'hết pin rồi' },
    { zh: '需要', pinyin: 'xūyào', viet: 'cần' },
    { zh: '找', pinyin: 'zhǎo', viet: 'tìm' },
    { zh: '地方', pinyin: 'dìfang', viet: 'chỗ' },
    { zh: '充电', pinyin: 'chōngdiàn', viet: 'sạc điện' },
  ],
  '人': [
    { zh: '这个', pinyin: 'zhège', viet: 'cái này / nơi này' },
    { zh: '城市', pinyin: 'chéngshì', viet: 'thành phố' },
    { zh: '的', pinyin: 'de', viet: '(trợ từ sở hữu)' },
    { zh: '人', pinyin: 'rén', viet: 'người' },
    { zh: '非常多', pinyin: 'fēicháng duō', viet: 'rất nhiều' },
    { zh: '到处', pinyin: 'dàochù', viet: 'khắp nơi' },
    { zh: '都', pinyin: 'dōu', viet: 'đều' },
    { zh: '很热闹', pinyin: 'hěn rènao', viet: 'rất náo nhiệt' },
  ],
  '学生': [
    { zh: '这个班', pinyin: 'zhège bān', viet: 'lớp này' },
    { zh: '有', pinyin: 'yǒu', viet: 'có' },
    { zh: '三十个', pinyin: 'sānshí gè', viet: 'ba mươi' },
    { zh: '学生', pinyin: 'xuésheng', viet: 'học sinh' },
    { zh: '大家', pinyin: 'dàjiā', viet: 'mọi người' },
    { zh: '学习', pinyin: 'xuéxí', viet: 'học tập' },
    { zh: '都', pinyin: 'dōu', viet: 'đều' },
    { zh: '很认真', pinyin: 'hěn rènzhēn', viet: 'rất chăm chỉ' },
  ],
  '老师': [
    { zh: '我们的', pinyin: 'wǒmen de', viet: 'của chúng tôi' },
    { zh: '老师', pinyin: 'lǎoshī', viet: 'giáo viên' },
    { zh: '对', pinyin: 'duì', viet: 'với' },
    { zh: '学生', pinyin: 'xuésheng', viet: 'học sinh' },
    { zh: '很有耐心', pinyin: 'hěn yǒu nàixīn', viet: 'rất kiên nhẫn' },
    { zh: '讲课', pinyin: 'jiǎngkè', viet: 'giảng bài' },
    { zh: '也', pinyin: 'yě', viet: 'cũng' },
    { zh: '很有意思', pinyin: 'hěn yǒuyìsi', viet: 'rất thú vị' },
  ],
  '医生': [
    { zh: '医生', pinyin: 'yīshēng', viet: 'bác sĩ' },
    { zh: '说', pinyin: 'shuō', viet: 'nói' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '需要', pinyin: 'xūyào', viet: 'cần' },
    { zh: '多休息', pinyin: 'duō xiūxi', viet: 'nghỉ ngơi nhiều hơn' },
    { zh: '不能', pinyin: 'bù néng', viet: 'không thể' },
    { zh: '工作', pinyin: 'gōngzuò', viet: 'làm việc' },
    { zh: '太多', pinyin: 'tài duō', viet: 'quá nhiều' },
  ],
  '朋友': [
    { zh: '周末', pinyin: 'zhōumò', viet: 'cuối tuần' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '和', pinyin: 'hé', viet: 'cùng' },
    { zh: '朋友们', pinyin: 'péngyoumen', viet: 'các bạn bè' },
    { zh: '一起', pinyin: 'yīqǐ', viet: 'cùng nhau' },
    { zh: '去吃', pinyin: 'qù chī', viet: 'đi ăn' },
    { zh: '火锅', pinyin: 'huǒguō', viet: 'lẩu' },
    { zh: '聊得很开心', pinyin: 'liáo de hěn kāixīn', viet: 'trò chuyện rất vui' },
  ],
  '同学': [
    { zh: '我的', pinyin: 'wǒ de', viet: 'của tôi' },
    { zh: '同学', pinyin: 'tóngxué', viet: 'bạn học' },
    { zh: '帮', pinyin: 'bāng', viet: 'giúp' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '复习了', pinyin: 'fùxí le', viet: 'đã ôn tập' },
    { zh: '考试内容', pinyin: 'kǎoshì nèiróng', viet: 'nội dung kỳ thi' },
    { zh: '真的', pinyin: 'zhēnde', viet: 'thật sự' },
    { zh: '很感谢', pinyin: 'hěn gǎnxiè', viet: 'rất biết ơn' },
  ],
  '工人': [
    { zh: '工厂里的', pinyin: 'gōngchǎng lǐ de', viet: 'trong nhà máy' },
    { zh: '工人', pinyin: 'gōngrén', viet: 'công nhân' },
    { zh: '每天', pinyin: 'měitiān', viet: 'mỗi ngày' },
    { zh: '早上', pinyin: 'zǎoshang', viet: 'buổi sáng' },
    { zh: '八点', pinyin: 'bā diǎn', viet: 'tám giờ' },
    { zh: '开始', pinyin: 'kāishǐ', viet: 'bắt đầu' },
    { zh: '上班', pinyin: 'shàngbān', viet: 'đi làm' },
  ],
  '老板': [
    { zh: '老板', pinyin: 'lǎobǎn', viet: 'ông chủ' },
    { zh: '今天', pinyin: 'jīntiān', viet: 'hôm nay' },
    { zh: '给我们', pinyin: 'gěi wǒmen', viet: 'cho chúng tôi' },
    { zh: '开会', pinyin: 'kāihuì', viet: 'họp' },
    { zh: '说', pinyin: 'shuō', viet: 'nói' },
    { zh: '下个月', pinyin: 'xià gè yuè', viet: 'tháng tới' },
    { zh: '要', pinyin: 'yào', viet: 'sẽ' },
    { zh: '增加工资', pinyin: 'zēngjiā gōngzī', viet: 'tăng lương' },
  ],
  '学校': [
    { zh: '我们的', pinyin: 'wǒmen de', viet: 'của chúng tôi' },
    { zh: '学校', pinyin: 'xuéxiào', viet: 'trường học' },
    { zh: '离', pinyin: 'lí', viet: 'cách' },
    { zh: '地铁站', pinyin: 'dìtiě zhàn', viet: 'ga tàu điện ngầm' },
    { zh: '很近', pinyin: 'hěn jìn', viet: 'rất gần' },
    { zh: '走路', pinyin: 'zǒulù', viet: 'đi bộ' },
    { zh: '只要', pinyin: 'zhǐyào', viet: 'chỉ cần' },
    { zh: '五分钟', pinyin: 'wǔ fēnzhōng', viet: 'năm phút' },
  ],
  '书': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '喜欢', pinyin: 'xǐhuān', viet: 'thích' },
    { zh: '在', pinyin: 'zài', viet: 'ở / vào lúc' },
    { zh: '睡觉前', pinyin: 'shuìjiào qián', viet: 'trước khi ngủ' },
    { zh: '读', pinyin: 'dú', viet: 'đọc' },
    { zh: '一会儿', pinyin: 'yīhuìr', viet: 'một lúc' },
    { zh: '书', pinyin: 'shū', viet: 'sách' },
    { zh: '感觉', pinyin: 'gǎnjué', viet: 'cảm thấy' },
    { zh: '很放松', pinyin: 'hěn fàngsōng', viet: 'rất thư giãn' },
  ],
  '本子': [
    { zh: '老师', pinyin: 'lǎoshī', viet: 'giáo viên' },
    { zh: '让', pinyin: 'ràng', viet: 'yêu cầu / bảo' },
    { zh: '我们', pinyin: 'wǒmen', viet: 'chúng tôi' },
    { zh: '把', pinyin: 'bǎ', viet: '(giới từ chỉ đối tượng)' },
    { zh: '答案', pinyin: 'dáàn', viet: 'đáp án' },
    { zh: '写在', pinyin: 'xiě zài', viet: 'viết vào' },
    { zh: '本子上', pinyin: 'běnzi shàng', viet: 'trên vở' },
    { zh: '交给他', pinyin: 'jiāo gěi tā', viet: 'nộp cho thầy' },
  ],
  '笔': [
    { zh: '你', pinyin: 'nǐ', viet: 'bạn' },
    { zh: '能', pinyin: 'néng', viet: 'có thể' },
    { zh: '借', pinyin: 'jiè', viet: 'cho mượn' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '一支', pinyin: 'yī zhī', viet: 'một cái' },
    { zh: '笔', pinyin: 'bǐ', viet: 'bút' },
    { zh: '吗', pinyin: 'ma', viet: '(câu hỏi)' },
    { zh: '我需要', pinyin: 'wǒ xūyào', viet: 'tôi cần' },
    { zh: '签名字', pinyin: 'qiān míngzi', viet: 'ký tên' },
  ],
  '黑板': [
    { zh: '老师', pinyin: 'lǎoshī', viet: 'giáo viên' },
    { zh: '在', pinyin: 'zài', viet: 'ở trên' },
    { zh: '黑板上', pinyin: 'hēibǎn shàng', viet: 'trên bảng' },
    { zh: '写了', pinyin: 'xiě le', viet: 'đã viết' },
    { zh: '很多', pinyin: 'hěn duō', viet: 'rất nhiều' },
    { zh: '生词', pinyin: 'shēngcí', viet: 'từ mới' },
    { zh: '让我们', pinyin: 'ràng wǒmen', viet: 'bảo chúng tôi' },
    { zh: '抄下来', pinyin: 'chāo xiàlái', viet: 'chép lại' },
  ],
  '教室': [
    { zh: '上课铃', pinyin: 'shàngkè líng', viet: 'chuông vào lớp' },
    { zh: '响了', pinyin: 'xiǎng le', viet: 'vang lên rồi' },
    { zh: '同学们', pinyin: 'tóngxuémen', viet: 'các bạn học' },
    { zh: '都', pinyin: 'dōu', viet: 'đều' },
    { zh: '跑进', pinyin: 'pǎo jìn', viet: 'chạy vào' },
    { zh: '教室', pinyin: 'jiàoshì', viet: 'lớp học' },
    { zh: '坐好了', pinyin: 'zuò hǎo le', viet: 'đã ngồi vào chỗ' },
  ],
  '作业': [
    { zh: '今天的', pinyin: 'jīntiān de', viet: 'của hôm nay' },
    { zh: '作业', pinyin: 'zuòyè', viet: 'bài tập' },
    { zh: '很多', pinyin: 'hěn duō', viet: 'rất nhiều' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '做了', pinyin: 'zuò le', viet: 'đã làm' },
    { zh: '两个小时', pinyin: 'liǎng gè xiǎoshí', viet: 'hai tiếng đồng hồ' },
    { zh: '才', pinyin: 'cái', viet: 'mới' },
    { zh: '做完', pinyin: 'zuò wán', viet: 'làm xong' },
  ],
  '考试': [
    { zh: '下周', pinyin: 'xià zhōu', viet: 'tuần tới' },
    { zh: '有', pinyin: 'yǒu', viet: 'có' },
    { zh: '考试', pinyin: 'kǎoshì', viet: 'kỳ thi' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '每天晚上', pinyin: 'měitiān wǎnshàng', viet: 'mỗi tối' },
    { zh: '都', pinyin: 'dōu', viet: 'đều' },
    { zh: '在', pinyin: 'zài', viet: 'đang' },
    { zh: '认真复习', pinyin: 'rènzhēn fùxí', viet: 'ôn bài chăm chỉ' },
  ],
  '水': [
    { zh: '医生', pinyin: 'yīshēng', viet: 'bác sĩ' },
    { zh: '说', pinyin: 'shuō', viet: 'nói' },
    { zh: '每天', pinyin: 'měitiān', viet: 'mỗi ngày' },
    { zh: '要喝', pinyin: 'yào hē', viet: 'phải uống' },
    { zh: '八杯', pinyin: 'bā bēi', viet: 'tám ly' },
    { zh: '水', pinyin: 'shuǐ', viet: 'nước' },
    { zh: '对身体', pinyin: 'duì shēntǐ', viet: 'cho cơ thể' },
    { zh: '很好', pinyin: 'hěn hǎo', viet: 'rất tốt' },
  ],
  '米饭': [
    { zh: '我们家', pinyin: 'wǒmen jiā', viet: 'nhà chúng tôi' },
    { zh: '每天', pinyin: 'měitiān', viet: 'mỗi ngày' },
    { zh: '中午', pinyin: 'zhōngwǔ', viet: 'buổi trưa' },
    { zh: '都吃', pinyin: 'dōu chī', viet: 'đều ăn' },
    { zh: '米饭', pinyin: 'mǐfàn', viet: 'cơm' },
    { zh: '配菜', pinyin: 'pèi cài', viet: 'với thức ăn' },
    { zh: '很简单', pinyin: 'hěn jiǎndān', viet: 'rất đơn giản' },
    { zh: '但', pinyin: 'dàn', viet: 'nhưng' },
    { zh: '很好吃', pinyin: 'hěn hǎochī', viet: 'rất ngon' },
  ],
  '面条': [
    { zh: '天冷的时候', pinyin: 'tiān lěng de shíhou', viet: 'khi trời lạnh' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '最喜欢', pinyin: 'zuì xǐhuān', viet: 'thích nhất' },
    { zh: '吃', pinyin: 'chī', viet: 'ăn' },
    { zh: '一碗', pinyin: 'yī wǎn', viet: 'một bát' },
    { zh: '热腾腾的', pinyin: 'rètēngténg de', viet: 'nóng hổi' },
    { zh: '面条', pinyin: 'miàntiáo', viet: 'mì' },
  ],
  '苹果': [
    { zh: '妈妈', pinyin: 'māma', viet: 'mẹ' },
    { zh: '每天', pinyin: 'měitiān', viet: 'mỗi ngày' },
    { zh: '都', pinyin: 'dōu', viet: 'đều' },
    { zh: '给我', pinyin: 'gěi wǒ', viet: 'cho tôi' },
    { zh: '带', pinyin: 'dài', viet: 'mang' },
    { zh: '一个', pinyin: 'yī gè', viet: 'một quả' },
    { zh: '苹果', pinyin: 'píngguǒ', viet: 'táo' },
    { zh: '当零食吃', pinyin: 'dāng língshí chī', viet: 'để ăn vặt' },
  ],
  '香蕉': [
    { zh: '这串', pinyin: 'zhè chuàn', viet: 'nải này' },
    { zh: '香蕉', pinyin: 'xiāngjiāo', viet: 'chuối' },
    { zh: '又甜', pinyin: 'yòu tián', viet: 'vừa ngọt' },
    { zh: '又软', pinyin: 'yòu ruǎn', viet: 'vừa mềm' },
    { zh: '是', pinyin: 'shì', viet: 'là' },
    { zh: '今天早上', pinyin: 'jīntiān zǎoshang', viet: 'sáng nay' },
    { zh: '刚买的', pinyin: 'gāng mǎi de', viet: 'vừa mới mua' },
  ],
  '蔬菜': [
    { zh: '多吃', pinyin: 'duō chī', viet: 'ăn nhiều' },
    { zh: '蔬菜', pinyin: 'shūcài', viet: 'rau' },
    { zh: '对健康', pinyin: 'duì jiànkāng', viet: 'cho sức khỏe' },
    { zh: '有好处', pinyin: 'yǒu hǎochù', viet: 'có lợi' },
    { zh: '每天', pinyin: 'měitiān', viet: 'mỗi ngày' },
    { zh: '要吃', pinyin: 'yào chī', viet: 'cần ăn' },
    { zh: '足够的量', pinyin: 'zúgòu de liàng', viet: 'đủ lượng cần thiết' },
  ],
  '鸡蛋': [
    { zh: '早餐', pinyin: 'zǎocān', viet: 'bữa sáng' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '喜欢吃', pinyin: 'xǐhuān chī', viet: 'thích ăn' },
    { zh: '两个', pinyin: 'liǎng gè', viet: 'hai quả' },
    { zh: '煮鸡蛋', pinyin: 'zhǔ jīdàn', viet: 'trứng luộc' },
    { zh: '和', pinyin: 'hé', viet: 'và' },
    { zh: '一杯牛奶', pinyin: 'yī bēi niúnǎi', viet: 'một ly sữa' },
  ],
  '茶': [
    { zh: '爷爷', pinyin: 'yéye', viet: 'ông nội' },
    { zh: '每天早上', pinyin: 'měitiān zǎoshang', viet: 'mỗi sáng' },
    { zh: '都会', pinyin: 'dōu huì', viet: 'đều sẽ' },
    { zh: '泡', pinyin: 'pào', viet: 'pha' },
    { zh: '一壶', pinyin: 'yī hú', viet: 'một ấm' },
    { zh: '茶', pinyin: 'chá', viet: 'trà' },
    { zh: '慢慢喝', pinyin: 'mànmàn hē', viet: 'uống từ từ' },
  ],
  '中国': [
    { zh: '中国', pinyin: 'Zhōngguó', viet: 'Trung Quốc' },
    { zh: '是', pinyin: 'shì', viet: 'là' },
    { zh: '世界上', pinyin: 'shìjiè shàng', viet: 'trên thế giới' },
    { zh: '人口', pinyin: 'rénkǒu', viet: 'dân số' },
    { zh: '最多的', pinyin: 'zuì duō de', viet: 'đông nhất' },
    { zh: '国家', pinyin: 'guójiā', viet: 'quốc gia' },
    { zh: '之一', pinyin: 'zhī yī', viet: 'một trong số' },
  ],
  '城市': [
    { zh: '上海', pinyin: 'Shànghǎi', viet: 'Thượng Hải' },
    { zh: '是', pinyin: 'shì', viet: 'là' },
    { zh: '中国', pinyin: 'Zhōngguó', viet: 'Trung Quốc' },
    { zh: '最繁华的', pinyin: 'zuì fánhuá de', viet: 'phồn hoa nhất' },
    { zh: '城市之一', pinyin: 'chéngshì zhī yī', viet: 'một trong những thành phố' },
    { zh: '到处', pinyin: 'dàochù', viet: 'đâu đâu' },
    { zh: '都是', pinyin: 'dōu shì', viet: 'đều là' },
    { zh: '高楼大厦', pinyin: 'gāolóu dàshà', viet: 'nhà cao tầng' },
  ],
  '商店': [
    { zh: '街上', pinyin: 'jiē shàng', viet: 'trên phố' },
    { zh: '有很多', pinyin: 'yǒu hěn duō', viet: 'có rất nhiều' },
    { zh: '商店', pinyin: 'shāngdiàn', viet: 'cửa hàng' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '找了很久', pinyin: 'zhǎo le hěn jiǔ', viet: 'tìm mãi' },
    { zh: '才找到', pinyin: 'cái zhǎodào', viet: 'mới thấy' },
    { zh: '卖鞋的', pinyin: 'mài xié de', viet: 'bán giày' },
    { zh: '那家', pinyin: 'nà jiā', viet: 'cửa hàng đó' },
  ],
  '公园': [
    { zh: '周末早上', pinyin: 'zhōumò zǎoshang', viet: 'sáng cuối tuần' },
    { zh: '很多人', pinyin: 'hěn duō rén', viet: 'nhiều người' },
    { zh: '去', pinyin: 'qù', viet: 'ra / đến' },
    { zh: '公园', pinyin: 'gōngyuán', viet: 'công viên' },
    { zh: '散步', pinyin: 'sànbù', viet: 'đi dạo' },
    { zh: '或者', pinyin: 'huòzhě', viet: 'hoặc' },
    { zh: '打太极拳', pinyin: 'dǎ tàijíquán', viet: 'tập thái cực quyền' },
  ],
  '山': [
    { zh: '这座山', pinyin: 'zhè zuò shān', viet: 'ngọn núi này' },
    { zh: '很高', pinyin: 'hěn gāo', viet: 'rất cao' },
    { zh: '爬到', pinyin: 'pá dào', viet: 'leo lên đến' },
    { zh: '山顶', pinyin: 'shāndǐng', viet: 'đỉnh núi' },
    { zh: '需要', pinyin: 'xūyào', viet: 'cần' },
    { zh: '三个多小时', pinyin: 'sān gè duō xiǎoshí', viet: 'hơn ba tiếng' },
  ],
  '河': [
    { zh: '这条河', pinyin: 'zhè tiáo hé', viet: 'con sông này' },
    { zh: '的水', pinyin: 'de shuǐ', viet: 'nước' },
    { zh: '很清澈', pinyin: 'hěn qīngchè', viet: 'rất trong' },
    { zh: '两边', pinyin: 'liǎng biān', viet: 'hai bên' },
    { zh: '种了', pinyin: 'zhòng le', viet: 'đã trồng' },
    { zh: '很多树', pinyin: 'hěn duō shù', viet: 'rất nhiều cây' },
  ],
  '海': [
    { zh: '夏天', pinyin: 'xiàtiān', viet: 'mùa hè' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '最喜欢', pinyin: 'zuì xǐhuān', viet: 'thích nhất' },
    { zh: '去', pinyin: 'qù', viet: 'ra / đến' },
    { zh: '海边', pinyin: 'hǎibiān', viet: 'bờ biển' },
    { zh: '游泳', pinyin: 'yóuyǒng', viet: 'bơi lội' },
    { zh: '感觉', pinyin: 'gǎnjué', viet: 'cảm giác' },
    { zh: '非常舒服', pinyin: 'fēicháng shūfu', viet: 'rất dễ chịu' },
  ],
  '天空': [
    { zh: '今天', pinyin: 'jīntiān', viet: 'hôm nay' },
    { zh: '天空', pinyin: 'tiānkōng', viet: 'bầu trời' },
    { zh: '很蓝', pinyin: 'hěn lán', viet: 'rất xanh' },
    { zh: '一朵云', pinyin: 'yī duǒ yún', viet: 'một đám mây' },
    { zh: '也没有', pinyin: 'yě méiyǒu', viet: 'cũng không có' },
    { zh: '天气', pinyin: 'tiānqì', viet: 'thời tiết' },
    { zh: '非常好', pinyin: 'fēicháng hǎo', viet: 'rất đẹp' },
  ],
  '时间': [
    { zh: '时间', pinyin: 'shíjiān', viet: 'thời gian' },
    { zh: '过得', pinyin: 'guò de', viet: 'trôi' },
    { zh: '很快', pinyin: 'hěn kuài', viet: 'rất nhanh' },
    { zh: '不知不觉', pinyin: 'bùzhī bùjué', viet: 'không hay biết' },
    { zh: '已经', pinyin: 'yǐjīng', viet: 'đã' },
    { zh: '到了', pinyin: 'dào le', viet: 'đến rồi' },
    { zh: '年底', pinyin: 'niándǐ', viet: 'cuối năm' },
  ],
  '今天': [
    { zh: '今天', pinyin: 'jīntiān', viet: 'hôm nay' },
    { zh: '是', pinyin: 'shì', viet: 'là' },
    { zh: '我的', pinyin: 'wǒ de', viet: 'của tôi' },
    { zh: '生日', pinyin: 'shēngrì', viet: 'sinh nhật' },
    { zh: '朋友们', pinyin: 'péngyoumen', viet: 'các bạn bè' },
    { zh: '给我', pinyin: 'gěi wǒ', viet: 'cho tôi' },
    { zh: '买了', pinyin: 'mǎi le', viet: 'đã mua' },
    { zh: '一个大蛋糕', pinyin: 'yī gè dà dàngāo', viet: 'một chiếc bánh kem to' },
  ],
  '明天': [
    { zh: '明天', pinyin: 'míngtiān', viet: 'ngày mai' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '要去', pinyin: 'yào qù', viet: 'sẽ đi' },
    { zh: '面试', pinyin: 'miànshì', viet: 'phỏng vấn' },
    { zh: '今晚', pinyin: 'jīn wǎn', viet: 'tối nay' },
    { zh: '需要', pinyin: 'xūyào', viet: 'cần' },
    { zh: '好好准备', pinyin: 'hǎohǎo zhǔnbèi', viet: 'chuẩn bị thật kỹ' },
  ],
  '昨天': [
    { zh: '昨天', pinyin: 'zuótiān', viet: 'hôm qua' },
    { zh: '下了', pinyin: 'xià le', viet: 'đã mưa / rơi' },
    { zh: '一天的雨', pinyin: 'yī tiān de yǔ', viet: 'mưa cả ngày' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '没有', pinyin: 'méiyǒu', viet: 'không' },
    { zh: '出门', pinyin: 'chūmén', viet: 'ra ngoài' },
  ],
  '上午': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '每天', pinyin: 'měitiān', viet: 'mỗi ngày' },
    { zh: '上午', pinyin: 'shàngwǔ', viet: 'buổi sáng' },
    { zh: '九点', pinyin: 'jiǔ diǎn', viet: 'chín giờ' },
    { zh: '到公司', pinyin: 'dào gōngsī', viet: 'đến công ty' },
    { zh: '先', pinyin: 'xiān', viet: 'trước' },
    { zh: '喝杯咖啡', pinyin: 'hē bēi kāfēi', viet: 'uống ly cà phê' },
    { zh: '再开始', pinyin: 'zài kāishǐ', viet: 'rồi mới bắt đầu' },
    { zh: '工作', pinyin: 'gōngzuò', viet: 'làm việc' },
  ],
  '下午': [
    { zh: '下午', pinyin: 'xiàwǔ', viet: 'buổi chiều' },
    { zh: '三点', pinyin: 'sān diǎn', viet: 'ba giờ' },
    { zh: '我们', pinyin: 'wǒmen', viet: 'chúng ta' },
    { zh: '有', pinyin: 'yǒu', viet: 'có' },
    { zh: '一个', pinyin: 'yī gè', viet: 'một' },
    { zh: '重要的', pinyin: 'zhòngyào de', viet: 'quan trọng' },
    { zh: '会议', pinyin: 'huìyì', viet: 'cuộc họp' },
    { zh: '请', pinyin: 'qǐng', viet: 'xin' },
    { zh: '准时参加', pinyin: 'zhǔnshí cānjiā', viet: 'tham dự đúng giờ' },
  ],
  '晚上': [
    { zh: '晚上', pinyin: 'wǎnshàng', viet: 'buổi tối' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '喜欢', pinyin: 'xǐhuān', viet: 'thích' },
    { zh: '在', pinyin: 'zài', viet: 'ở' },
    { zh: '公园', pinyin: 'gōngyuán', viet: 'công viên' },
    { zh: '散步', pinyin: 'sànbù', viet: 'đi dạo' },
    { zh: '呼吸', pinyin: 'hūxī', viet: 'hít thở' },
    { zh: '新鲜空气', pinyin: 'xīnxiān kōngqì', viet: 'không khí trong lành' },
  ],
  '星期': [
    { zh: '这个星期', pinyin: 'zhège xīngqī', viet: 'tuần này' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '很忙', pinyin: 'hěn máng', viet: 'rất bận' },
    { zh: '每天', pinyin: 'měitiān', viet: 'mỗi ngày' },
    { zh: '都要', pinyin: 'dōu yào', viet: 'đều phải' },
    { zh: '加班', pinyin: 'jiābān', viet: 'làm thêm giờ' },
    { zh: '到很晚', pinyin: 'dào hěn wǎn', viet: 'đến rất khuya' },
  ],
  '电脑': [
    { zh: '我的', pinyin: 'wǒ de', viet: 'của tôi' },
    { zh: '电脑', pinyin: 'diànnǎo', viet: 'máy tính' },
    { zh: '坏了', pinyin: 'huài le', viet: 'hỏng rồi' },
    { zh: '需要', pinyin: 'xūyào', viet: 'cần' },
    { zh: '拿去修', pinyin: 'ná qù xiū', viet: 'mang đi sửa' },
    { zh: '现在', pinyin: 'xiànzài', viet: 'bây giờ' },
    { zh: '只能', pinyin: 'zhǐ néng', viet: 'chỉ có thể' },
    { zh: '用手机', pinyin: 'yòng shǒujī', viet: 'dùng điện thoại' },
    { zh: '工作', pinyin: 'gōngzuò', viet: 'làm việc' },
  ],
  '鼠标': [
    { zh: '我的', pinyin: 'wǒ de', viet: 'của tôi' },
    { zh: '鼠标', pinyin: 'shǔbiāo', viet: 'chuột' },
    { zh: '没有反应了', pinyin: 'méiyǒu fǎnyìng le', viet: 'không phản hồi nữa' },
    { zh: '可能', pinyin: 'kěnéng', viet: 'có thể' },
    { zh: '需要', pinyin: 'xūyào', viet: 'cần' },
    { zh: '换新电池', pinyin: 'huàn xīn diànchí', viet: 'thay pin mới' },
  ],
  '键盘': [
    { zh: '这个', pinyin: 'zhège', viet: 'cái này' },
    { zh: '机械键盘', pinyin: 'jīxiè jiànpán', viet: 'bàn phím cơ' },
    { zh: '打字的', pinyin: 'dǎzì de', viet: 'gõ phím' },
    { zh: '声音', pinyin: 'shēngyīn', viet: 'âm thanh' },
    { zh: '很大', pinyin: 'hěn dà', viet: 'rất to' },
    { zh: '但', pinyin: 'dàn', viet: 'nhưng' },
    { zh: '用起来', pinyin: 'yòng qǐlái', viet: 'khi dùng' },
    { zh: '很舒服', pinyin: 'hěn shūfu', viet: 'rất thoải mái' },
  ],
  '屏幕': [
    { zh: '这台电视', pinyin: 'zhè tái diànshì', viet: 'chiếc tivi này' },
    { zh: '的屏幕', pinyin: 'de píngmù', viet: 'màn hình' },
    { zh: '很大', pinyin: 'hěn dà', viet: 'rất lớn' },
    { zh: '看电影', pinyin: 'kàn diànyǐng', viet: 'xem phim' },
    { zh: '的效果', pinyin: 'de xiàoguǒ', viet: 'hiệu ứng' },
    { zh: '非常好', pinyin: 'fēicháng hǎo', viet: 'rất tốt' },
  ],
  '耳机': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '每天', pinyin: 'měitiān', viet: 'mỗi ngày' },
    { zh: '上班路上', pinyin: 'shàngbān lùshàng', viet: 'trên đường đi làm' },
    { zh: '都', pinyin: 'dōu', viet: 'đều' },
    { zh: '戴着', pinyin: 'dài zhe', viet: 'đeo' },
    { zh: '耳机', pinyin: 'ěrjī', viet: 'tai nghe' },
    { zh: '听音乐', pinyin: 'tīng yīnyuè', viet: 'nghe nhạc' },
    { zh: '或者', pinyin: 'huòzhě', viet: 'hoặc' },
    { zh: '播客', pinyin: 'bōkè', viet: 'podcast' },
  ],
  '衣服': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '买了', pinyin: 'mǎi le', viet: 'đã mua' },
    { zh: '一些', pinyin: 'yīxiē', viet: 'một ít' },
    { zh: '新衣服', pinyin: 'xīn yīfu', viet: 'quần áo mới' },
    { zh: '准备', pinyin: 'zhǔnbèi', viet: 'chuẩn bị' },
    { zh: '过年', pinyin: 'guònián', viet: 'dịp Tết' },
    { zh: '的时候', pinyin: 'de shíhou', viet: 'khi' },
    { zh: '穿', pinyin: 'chuān', viet: 'mặc' },
  ],
  '裤子': [
    { zh: '这条', pinyin: 'zhè tiáo', viet: 'chiếc này' },
    { zh: '裤子', pinyin: 'kùzi', viet: 'quần' },
    { zh: '太长了', pinyin: 'tài cháng le', viet: 'dài quá' },
    { zh: '需要', pinyin: 'xūyào', viet: 'cần' },
    { zh: '拿去', pinyin: 'ná qù', viet: 'mang đi' },
    { zh: '改短', pinyin: 'gǎi duǎn', viet: 'sửa cho ngắn' },
    { zh: '一点', pinyin: 'yīdiǎn', viet: 'một chút' },
  ],
  '鞋': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '在网上', pinyin: 'zài wǎng shàng', viet: 'trên mạng' },
    { zh: '买了', pinyin: 'mǎi le', viet: 'đã mua' },
    { zh: '一双', pinyin: 'yī shuāng', viet: 'một đôi' },
    { zh: '运动鞋', pinyin: 'yùndòngxié', viet: 'giày thể thao' },
    { zh: '穿起来', pinyin: 'chuān qǐlái', viet: 'khi mang vào' },
    { zh: '非常轻便', pinyin: 'fēicháng qīngbiàn', viet: 'rất nhẹ nhàng thoải mái' },
  ],
  '帽子': [
    { zh: '夏天', pinyin: 'xiàtiān', viet: 'mùa hè' },
    { zh: '出门', pinyin: 'chūmén', viet: 'ra ngoài' },
    { zh: '记得', pinyin: 'jìde', viet: 'nhớ' },
    { zh: '戴帽子', pinyin: 'dài màozi', viet: 'đội mũ' },
    { zh: '不然', pinyin: 'bùrán', viet: 'không thì' },
    { zh: '太阳', pinyin: 'tàiyáng', viet: 'nắng / mặt trời' },
    { zh: '会晒伤', pinyin: 'huì shài shāng', viet: 'sẽ làm cháy' },
    { zh: '皮肤', pinyin: 'pífū', viet: 'da' },
  ],
  '包': [
    { zh: '我的', pinyin: 'wǒ de', viet: 'của tôi' },
    { zh: '包里', pinyin: 'bāo lǐ', viet: 'trong túi' },
    { zh: '装着', pinyin: 'zhuāng zhe', viet: 'đựng' },
    { zh: '钱包', pinyin: 'qiánbāo', viet: 'ví tiền' },
    { zh: '手机', pinyin: 'shǒujī', viet: 'điện thoại' },
    { zh: '和', pinyin: 'hé', viet: 'và' },
    { zh: '一些', pinyin: 'yīxiē', viet: 'một số' },
    { zh: '重要文件', pinyin: 'zhòngyào wénjiàn', viet: 'giấy tờ quan trọng' },
  ],
  '汽车': [
    { zh: '爸爸', pinyin: 'bàba', viet: 'bố' },
    { zh: '买了', pinyin: 'mǎi le', viet: 'đã mua' },
    { zh: '一辆', pinyin: 'yī liàng', viet: 'một chiếc' },
    { zh: '新汽车', pinyin: 'xīn qìchē', viet: 'ô tô mới' },
    { zh: '周末', pinyin: 'zhōumò', viet: 'cuối tuần' },
    { zh: '带我们', pinyin: 'dài wǒmen', viet: 'chở chúng tôi' },
    { zh: '去', pinyin: 'qù', viet: 'đến' },
    { zh: '郊区', pinyin: 'jiāoqū', viet: 'ngoại ô' },
    { zh: '玩', pinyin: 'wán', viet: 'chơi' },
  ],
  '自行车': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '每天', pinyin: 'měitiān', viet: 'mỗi ngày' },
    { zh: '骑', pinyin: 'qí', viet: 'đạp / cưỡi' },
    { zh: '自行车', pinyin: 'zìxíngchē', viet: 'xe đạp' },
    { zh: '上班', pinyin: 'shàngbān', viet: 'đi làm' },
    { zh: '既', pinyin: 'jì', viet: 'vừa' },
    { zh: '环保', pinyin: 'huánbǎo', viet: 'bảo vệ môi trường' },
    { zh: '又', pinyin: 'yòu', viet: 'vừa' },
    { zh: '锻炼身体', pinyin: 'duànliàn shēntǐ', viet: 'rèn luyện sức khỏe' },
  ],
  '公交车': [
    { zh: '坐', pinyin: 'zuò', viet: 'đi (phương tiện)' },
    { zh: '公交车', pinyin: 'gōngjiāochē', viet: 'xe buýt' },
    { zh: '去', pinyin: 'qù', viet: 'đến' },
    { zh: '市中心', pinyin: 'shì zhōngxīn', viet: 'trung tâm thành phố' },
    { zh: '需要', pinyin: 'xūyào', viet: 'cần' },
    { zh: '大约', pinyin: 'dàyuē', viet: 'khoảng' },
    { zh: '四十分钟', pinyin: 'sìshí fēnzhōng', viet: 'bốn mươi phút' },
  ],
  '火车': [
    { zh: '我们', pinyin: 'wǒmen', viet: 'chúng tôi' },
    { zh: '订了', pinyin: 'dìng le', viet: 'đã đặt' },
    { zh: '高铁票', pinyin: 'gāotiě piào', viet: 'vé tàu cao tốc' },
    { zh: '坐火车', pinyin: 'zuò huǒchē', viet: 'đi tàu hỏa' },
    { zh: '去北京', pinyin: 'qù Běijīng', viet: 'lên Bắc Kinh' },
    { zh: '只需要', pinyin: 'zhǐ xūyào', viet: 'chỉ cần' },
    { zh: '两小时', pinyin: 'liǎng xiǎoshí', viet: 'hai tiếng' },
  ],
  '飞机': [
    { zh: '这', pinyin: 'zhè', viet: 'đây' },
    { zh: '是', pinyin: 'shì', viet: 'là' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '第一次', pinyin: 'dì yī cì', viet: 'lần đầu tiên' },
    { zh: '坐飞机', pinyin: 'zuò fēijī', viet: 'đi máy bay' },
    { zh: '飞行时间', pinyin: 'fēixíng shíjiān', viet: 'thời gian bay' },
    { zh: '大概', pinyin: 'dàgài', viet: 'khoảng' },
    { zh: '三个小时', pinyin: 'sān gè xiǎoshí', viet: 'ba tiếng' },
  ],
  '路': [
    { zh: '这条路', pinyin: 'zhè tiáo lù', viet: 'con đường này' },
    { zh: '正在修', pinyin: 'zhèngzài xiū', viet: 'đang sửa' },
    { zh: '所有车辆', pinyin: 'suǒyǒu chēliàng', viet: 'tất cả các xe' },
    { zh: '都要', pinyin: 'dōu yào', viet: 'đều phải' },
    { zh: '绕道', pinyin: 'ràodào', viet: 'đi đường vòng' },
    { zh: '通行', pinyin: 'tōngxíng', viet: 'lưu thông' },
  ],
  '桥': [
    { zh: '过了', pinyin: 'guò le', viet: 'qua rồi' },
    { zh: '这座桥', pinyin: 'zhè zuò qiáo', viet: 'cây cầu này' },
    { zh: '就到了', pinyin: 'jiù dào le', viet: 'là đến' },
    { zh: '村子', pinyin: 'cūnzi', viet: 'làng' },
    { zh: '里面', pinyin: 'lǐmiàn', viet: 'bên trong' },
    { zh: '有很多', pinyin: 'yǒu hěn duō', viet: 'có rất nhiều' },
    { zh: '古老的建筑', pinyin: 'gǔlǎo de jiànzhù', viet: 'công trình cổ xưa' },
  ],
  '地铁': [
    { zh: '坐', pinyin: 'zuò', viet: 'đi (phương tiện)' },
    { zh: '地铁', pinyin: 'dìtiě', viet: 'tàu điện ngầm' },
    { zh: '上班', pinyin: 'shàngbān', viet: 'đi làm' },
    { zh: '不堵车', pinyin: 'bù dǔchē', viet: 'không kẹt xe' },
    { zh: '比', pinyin: 'bǐ', viet: 'hơn' },
    { zh: '开车', pinyin: 'kāichē', viet: 'lái xe' },
    { zh: '快多了', pinyin: 'kuài duō le', viet: 'nhanh hơn nhiều' },
  ],
  '站': [
    { zh: '请', pinyin: 'qǐng', viet: 'vui lòng' },
    { zh: '在', pinyin: 'zài', viet: 'ở' },
    { zh: '下一站', pinyin: 'xià yī zhàn', viet: 'trạm tiếp theo' },
    { zh: '下车', pinyin: 'xià chē', viet: 'xuống xe' },
    { zh: '出口', pinyin: 'chūkǒu', viet: 'lối ra' },
    { zh: '在左边', pinyin: 'zài zuǒbiān', viet: 'ở bên trái' },
  ],
  '机场': [
    { zh: '我们', pinyin: 'wǒmen', viet: 'chúng ta' },
    { zh: '需要', pinyin: 'xūyào', viet: 'cần' },
    { zh: '提前', pinyin: 'tíqián', viet: 'trước' },
    { zh: '两小时', pinyin: 'liǎng xiǎoshí', viet: 'hai tiếng' },
    { zh: '到', pinyin: 'dào', viet: 'đến' },
    { zh: '机场', pinyin: 'jīchǎng', viet: 'sân bay' },
    { zh: '办理', pinyin: 'bànlǐ', viet: 'làm' },
    { zh: '登机手续', pinyin: 'dēngjī shǒuxù', viet: 'thủ tục lên máy bay' },
  ],
  '市场': [
    { zh: '妈妈', pinyin: 'māma', viet: 'mẹ' },
    { zh: '每天早上', pinyin: 'měitiān zǎoshang', viet: 'mỗi sáng' },
    { zh: '都', pinyin: 'dōu', viet: 'đều' },
    { zh: '去', pinyin: 'qù', viet: 'ra' },
    { zh: '市场', pinyin: 'shìchǎng', viet: 'chợ' },
    { zh: '买', pinyin: 'mǎi', viet: 'mua' },
    { zh: '新鲜的', pinyin: 'xīnxiān de', viet: 'tươi' },
    { zh: '蔬菜和水果', pinyin: 'shūcài hé shuǐguǒ', viet: 'rau và trái cây' },
  ],
  '超市': [
    { zh: '周末', pinyin: 'zhōumò', viet: 'cuối tuần' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '去超市', pinyin: 'qù chāoshì', viet: 'đi siêu thị' },
    { zh: '买了', pinyin: 'mǎi le', viet: 'đã mua' },
    { zh: '一周需要的', pinyin: 'yī zhōu xūyào de', viet: 'cần cho cả tuần' },
    { zh: '食材', pinyin: 'shícái', viet: 'nguyên liệu nấu ăn' },
    { zh: '和', pinyin: 'hé', viet: 'và' },
    { zh: '生活用品', pinyin: 'shēnghuó yòngpǐn', viet: 'đồ dùng sinh hoạt' },
  ],
  '商场': [
    { zh: '这家商场', pinyin: 'zhè jiā shāngchǎng', viet: 'trung tâm thương mại này' },
    { zh: '有五层', pinyin: 'yǒu wǔ céng', viet: 'có năm tầng' },
    { zh: '里面', pinyin: 'lǐmiàn', viet: 'bên trong' },
    { zh: '有', pinyin: 'yǒu', viet: 'có' },
    { zh: '餐厅', pinyin: 'cāntīng', viet: 'nhà hàng' },
    { zh: '电影院', pinyin: 'diànyǐngyuàn', viet: 'rạp chiếu phim' },
    { zh: '和', pinyin: 'hé', viet: 'và' },
    { zh: '很多名牌店', pinyin: 'hěn duō míngpái diàn', viet: 'nhiều cửa hàng thương hiệu nổi tiếng' },
  ],
  '菜市场': [
    { zh: '菜市场的', pinyin: 'cài shìchǎng de', viet: 'ở chợ rau' },
    { zh: '蔬菜', pinyin: 'shūcài', viet: 'rau' },
    { zh: '比', pinyin: 'bǐ', viet: 'hơn' },
    { zh: '超市', pinyin: 'chāoshì', viet: 'siêu thị' },
    { zh: '新鲜', pinyin: 'xīnxiān', viet: 'tươi hơn' },
    { zh: '价格', pinyin: 'jiàgé', viet: 'giá' },
    { zh: '也', pinyin: 'yě', viet: 'cũng' },
    { zh: '便宜一些', pinyin: 'piányí yīxiē', viet: 'rẻ hơn một chút' },
  ],
  '水果': [
    { zh: '这家店的', pinyin: 'zhè jiā diàn de', viet: 'của cửa hàng này' },
    { zh: '水果', pinyin: 'shuǐguǒ', viet: 'trái cây' },
    { zh: '很新鲜', pinyin: 'hěn xīnxiān', viet: 'rất tươi' },
    { zh: '而且', pinyin: 'érqiě', viet: 'hơn nữa' },
    { zh: '种类', pinyin: 'zhǒnglèi', viet: 'chủng loại' },
    { zh: '非常多', pinyin: 'fēicháng duō', viet: 'rất phong phú' },
  ],
  '肉': [
    { zh: '今天', pinyin: 'jīntiān', viet: 'hôm nay' },
    { zh: '妈妈', pinyin: 'māma', viet: 'mẹ' },
    { zh: '买了', pinyin: 'mǎi le', viet: 'đã mua' },
    { zh: '一斤', pinyin: 'yī jīn', viet: 'nửa kilogram' },
    { zh: '猪肉', pinyin: 'zhūròu', viet: 'thịt lợn' },
    { zh: '准备做', pinyin: 'zhǔnbèi zuò', viet: 'chuẩn bị làm' },
    { zh: '红烧肉', pinyin: 'hóngshāo ròu', viet: 'thịt kho' },
  ],
  '鱼': [
    { zh: '爸爸', pinyin: 'bàba', viet: 'bố' },
    { zh: '很喜欢', pinyin: 'hěn xǐhuān', viet: 'rất thích' },
    { zh: '吃鱼', pinyin: 'chī yú', viet: 'ăn cá' },
    { zh: '妈妈', pinyin: 'māma', viet: 'mẹ' },
    { zh: '每周', pinyin: 'měi zhōu', viet: 'mỗi tuần' },
    { zh: '都会做', pinyin: 'dōu huì zuò', viet: 'đều làm' },
    { zh: '一次', pinyin: 'yī cì', viet: 'một lần' },
    { zh: '清蒸鱼', pinyin: 'qīngzhēng yú', viet: 'cá hấp' },
  ],
  '牛奶': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '每天早上', pinyin: 'měitiān zǎoshang', viet: 'mỗi sáng' },
    { zh: '都', pinyin: 'dōu', viet: 'đều' },
    { zh: '喝', pinyin: 'hē', viet: 'uống' },
    { zh: '一杯牛奶', pinyin: 'yī bēi niúnǎi', viet: 'một ly sữa' },
    { zh: '对骨骼', pinyin: 'duì gǔgé', viet: 'cho xương' },
    { zh: '很有好处', pinyin: 'hěn yǒu hǎochù', viet: 'rất có lợi' },
  ],
  '网店': [
    { zh: '她', pinyin: 'tā', viet: 'cô ấy' },
    { zh: '开了', pinyin: 'kāi le', viet: 'đã mở' },
    { zh: '一家', pinyin: 'yī jiā', viet: 'một' },
    { zh: '专卖', pinyin: 'zhuān mài', viet: 'chuyên bán' },
    { zh: '手工饰品的', pinyin: 'shǒugōng shìpǐn de', viet: 'đồ trang sức thủ công' },
    { zh: '网店', pinyin: 'wǎngdiàn', viet: 'cửa hàng online' },
    { zh: '生意', pinyin: 'shēngyi', viet: 'việc kinh doanh' },
    { zh: '越来越好', pinyin: 'yuè lái yuè hǎo', viet: 'ngày càng tốt hơn' },
  ],
  '平台': [
    { zh: '这个', pinyin: 'zhège', viet: 'cái này' },
    { zh: '电商平台', pinyin: 'diànshāng píngtái', viet: 'nền tảng thương mại điện tử' },
    { zh: '有很多', pinyin: 'yǒu hěn duō', viet: 'có rất nhiều' },
    { zh: '优惠活动', pinyin: 'yōuhuì huódòng', viet: 'chương trình khuyến mãi' },
    { zh: '很多人', pinyin: 'hěn duō rén', viet: 'nhiều người' },
    { zh: '都在', pinyin: 'dōu zài', viet: 'đều ở' },
    { zh: '上面', pinyin: 'shàngmiàn', viet: 'trên đó' },
    { zh: '购物', pinyin: 'gòuwù', viet: 'mua sắm' },
  ],
  '卖家': [
    { zh: '这个卖家', pinyin: 'zhège màijiā', viet: 'người bán này' },
    { zh: '的服务', pinyin: 'de fúwù', viet: 'dịch vụ' },
    { zh: '态度', pinyin: 'tàidu', viet: 'thái độ' },
    { zh: '很好', pinyin: 'hěn hǎo', viet: 'rất tốt' },
    { zh: '发货', pinyin: 'fāhuò', viet: 'giao hàng' },
    { zh: '也很快', pinyin: 'yě hěn kuài', viet: 'cũng rất nhanh' },
  ],
  '买家': [
    { zh: '买家', pinyin: 'mǎijiā', viet: 'người mua' },
    { zh: '收到', pinyin: 'shōudào', viet: 'nhận được' },
    { zh: '商品后', pinyin: 'shāngpǐn hòu', viet: 'hàng rồi' },
    { zh: '对质量', pinyin: 'duì zhìliàng', viet: 'về chất lượng' },
    { zh: '非常满意', pinyin: 'fēicháng mǎnyì', viet: 'rất hài lòng' },
    { zh: '给了', pinyin: 'gěi le', viet: 'đã cho' },
    { zh: '五星好评', pinyin: 'wǔxīng hǎopíng', viet: 'đánh giá năm sao' },
  ],
  '快递': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '昨天', pinyin: 'zuótiān', viet: 'hôm qua' },
    { zh: '下单', pinyin: 'xià dān', viet: 'đặt hàng' },
    { zh: '今天', pinyin: 'jīntiān', viet: 'hôm nay' },
    { zh: '快递', pinyin: 'kuàidì', viet: 'hàng giao nhanh' },
    { zh: '就到了', pinyin: 'jiù dào le', viet: 'đã đến rồi' },
    { zh: '速度', pinyin: 'sùdù', viet: 'tốc độ' },
    { zh: '真的很快', pinyin: 'zhēnde hěn kuài', viet: 'thật sự rất nhanh' },
  ],
  '包裹': [
    { zh: '我的', pinyin: 'wǒ de', viet: 'của tôi' },
    { zh: '包裹', pinyin: 'bāoguǒ', viet: 'bưu kiện' },
    { zh: '已经', pinyin: 'yǐjīng', viet: 'đã' },
    { zh: '到了', pinyin: 'dào le', viet: 'đến rồi' },
    { zh: '快递站', pinyin: 'kuàidì zhàn', viet: 'điểm giao hàng' },
    { zh: '下午', pinyin: 'xiàwǔ', viet: 'buổi chiều' },
    { zh: '可以去取', pinyin: 'kěyǐ qù qǔ', viet: 'có thể đi lấy' },
  ],
  '订单': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '刚刚', pinyin: 'gānggāng', viet: 'vừa mới' },
    { zh: '查了一下', pinyin: 'chá le yīxià', viet: 'kiểm tra' },
    { zh: '我的订单', pinyin: 'wǒ de dìngdān', viet: 'đơn hàng của tôi' },
    { zh: '已经', pinyin: 'yǐjīng', viet: 'đã' },
    { zh: '发货了', pinyin: 'fāhuò le', viet: 'được giao đi rồi' },
    { zh: '明天', pinyin: 'míngtiān', viet: 'ngày mai' },
    { zh: '能到', pinyin: 'néng dào', viet: 'có thể nhận' },
  ],
  '购物车': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '把', pinyin: 'bǎ', viet: '(giới từ)' },
    { zh: '喜欢的', pinyin: 'xǐhuān de', viet: 'những món thích' },
    { zh: '商品', pinyin: 'shāngpǐn', viet: 'hàng hóa' },
    { zh: '加入', pinyin: 'jiārù', viet: 'thêm vào' },
    { zh: '购物车', pinyin: 'gòuwùchē', viet: 'giỏ hàng' },
    { zh: '等', pinyin: 'děng', viet: 'đợi' },
    { zh: '打折的时候', pinyin: 'dǎzhé de shíhou', viet: 'khi giảm giá' },
    { zh: '再付款', pinyin: 'zài fùkuǎn', viet: 'rồi mới thanh toán' },
  ],
  '商品': [
    { zh: '这家店的', pinyin: 'zhè jiā diàn de', viet: 'của cửa hàng này' },
    { zh: '商品', pinyin: 'shāngpǐn', viet: 'sản phẩm' },
    { zh: '质量很好', pinyin: 'zhìliàng hěn hǎo', viet: 'chất lượng tốt' },
    { zh: '价格', pinyin: 'jiàgé', viet: 'giá' },
    { zh: '也合理', pinyin: 'yě hélǐ', viet: 'cũng hợp lý' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '经常', pinyin: 'jīngcháng', viet: 'thường xuyên' },
    { zh: '在这里', pinyin: 'zài zhèlǐ', viet: 'ở đây' },
    { zh: '买东西', pinyin: 'mǎi dōngxi', viet: 'mua đồ' },
  ],
  '价格': [
    { zh: '这件衣服', pinyin: 'zhè jiàn yīfu', viet: 'chiếc áo này' },
    { zh: '的价格', pinyin: 'de jiàgé', viet: 'giá' },
    { zh: '有点贵', pinyin: 'yǒudiǎn guì', viet: 'hơi đắt' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '想', pinyin: 'xiǎng', viet: 'muốn' },
    { zh: '再比较一下', pinyin: 'zài bǐjiào yīxià', viet: 'so sánh thêm' },
    { zh: '其他店', pinyin: 'qítā diàn', viet: 'các cửa hàng khác' },
  ],
  '工厂': [
    { zh: '这个工厂', pinyin: 'zhège gōngchǎng', viet: 'nhà máy này' },
    { zh: '专门', pinyin: 'zhuānmén', viet: 'chuyên' },
    { zh: '生产', pinyin: 'shēngchǎn', viet: 'sản xuất' },
    { zh: '电子产品', pinyin: 'diànzǐ chǎnpǐn', viet: 'sản phẩm điện tử' },
    { zh: '每年', pinyin: 'měi nián', viet: 'mỗi năm' },
    { zh: '出口到', pinyin: 'chūkǒu dào', viet: 'xuất khẩu sang' },
    { zh: '很多国家', pinyin: 'hěn duō guójiā', viet: 'nhiều quốc gia' },
  ],
  '车间': [
    { zh: '车间里的', pinyin: 'chējiān lǐ de', viet: 'trong xưởng' },
    { zh: '工人', pinyin: 'gōngrén', viet: 'công nhân' },
    { zh: '都', pinyin: 'dōu', viet: 'đều' },
    { zh: '戴着', pinyin: 'dài zhe', viet: 'đội / đeo' },
    { zh: '安全帽', pinyin: 'ānquánmào', viet: 'mũ bảo hiểm' },
    { zh: '和手套', pinyin: 'hé shǒutào', viet: 'và găng tay' },
    { zh: '进行操作', pinyin: 'jìnxíng cāozuò', viet: 'khi vận hành' },
  ],
  '仓库': [
    { zh: '仓库里', pinyin: 'cāngkù lǐ', viet: 'trong kho' },
    { zh: '存放着', pinyin: 'cúnfàng zhe', viet: 'có dự trữ' },
    { zh: '大量的', pinyin: 'dàliàng de', viet: 'lượng lớn' },
    { zh: '原材料', pinyin: 'yuáncáiliào', viet: 'nguyên liệu thô' },
    { zh: '够用', pinyin: 'gòu yòng', viet: 'đủ dùng' },
    { zh: '三个月左右', pinyin: 'sān gè yuè zuǒyòu', viet: 'khoảng ba tháng' },
  ],
  '生产线': [
    { zh: '工厂', pinyin: 'gōngchǎng', viet: 'nhà máy' },
    { zh: '新增了', pinyin: 'xīn zēng le', viet: 'đã bổ sung thêm' },
    { zh: '一条', pinyin: 'yī tiáo', viet: 'một' },
    { zh: '自动化', pinyin: 'zìdònghuà', viet: 'tự động hóa' },
    { zh: '生产线', pinyin: 'shēngchǎnxiàn', viet: 'dây chuyền sản xuất' },
    { zh: '大大', pinyin: 'dàdà', viet: 'đáng kể' },
    { zh: '提高了', pinyin: 'tígāo le', viet: 'nâng cao' },
    { zh: '生产效率', pinyin: 'shēngchǎn xiàolǜ', viet: 'hiệu suất sản xuất' },
  ],
  '设备': [
    { zh: '这台设备', pinyin: 'zhè tái shèbèi', viet: 'thiết bị này' },
    { zh: '出了', pinyin: 'chū le', viet: 'xảy ra' },
    { zh: '故障', pinyin: 'gùzhàng', viet: 'sự cố' },
    { zh: '需要', pinyin: 'xūyào', viet: 'cần' },
    { zh: '马上', pinyin: 'mǎshàng', viet: 'ngay lập tức' },
    { zh: '联系', pinyin: 'liánxì', viet: 'liên hệ' },
    { zh: '技术员', pinyin: 'jìshùyuán', viet: 'kỹ thuật viên' },
    { zh: '来检修', pinyin: 'lái jiǎnxiū', viet: 'đến kiểm tra sửa chữa' },
  ],
  '技术员': [
    { zh: '技术员', pinyin: 'jìshùyuán', viet: 'kỹ thuật viên' },
    { zh: '花了', pinyin: 'huā le', viet: 'mất' },
    { zh: '一个小时', pinyin: 'yī gè xiǎoshí', viet: 'một tiếng đồng hồ' },
    { zh: '修好了', pinyin: 'xiū hǎo le', viet: 'đã sửa xong' },
    { zh: '生产线上的', pinyin: 'shēngchǎnxiàn shàng de', viet: 'trên dây chuyền' },
    { zh: '故障设备', pinyin: 'gùzhàng shèbèi', viet: 'thiết bị bị sự cố' },
  ],
  '工程师': [
    { zh: '这位工程师', pinyin: 'zhè wèi gōngchéngshī', viet: 'vị kỹ sư này' },
    { zh: '设计了', pinyin: 'shèjì le', viet: 'đã thiết kế' },
    { zh: '一套', pinyin: 'yī tào', viet: 'một bộ' },
    { zh: '全新的', pinyin: 'quánxīn de', viet: 'hoàn toàn mới' },
    { zh: '生产流程', pinyin: 'shēngchǎn liúchéng', viet: 'quy trình sản xuất' },
    { zh: '节省了', pinyin: 'jiéshěng le', viet: 'đã tiết kiệm được' },
    { zh: '很多成本', pinyin: 'hěn duō chéngběn', viet: 'rất nhiều chi phí' },
  ],
  '管理员': [
    { zh: '仓库管理员', pinyin: 'cāngkù guǎnlǐyuán', viet: 'quản lý kho' },
    { zh: '每天', pinyin: 'měitiān', viet: 'mỗi ngày' },
    { zh: '都要', pinyin: 'dōu yào', viet: 'đều phải' },
    { zh: '核对', pinyin: 'héduì', viet: 'kiểm tra' },
    { zh: '货物的', pinyin: 'huòwù de', viet: 'của hàng hóa' },
    { zh: '数量', pinyin: 'shùliàng', viet: 'số lượng' },
    { zh: '和状态', pinyin: 'hé zhuàngtài', viet: 'và tình trạng' },
  ],
  '经理': [
    { zh: '经理', pinyin: 'jīnglǐ', viet: 'giám đốc' },
    { zh: '今天', pinyin: 'jīntiān', viet: 'hôm nay' },
    { zh: '开会', pinyin: 'kāihuì', viet: 'họp' },
    { zh: '宣布了', pinyin: 'xuānbù le', viet: 'đã công bố' },
    { zh: '公司', pinyin: 'gōngsī', viet: 'công ty' },
    { zh: '新的', pinyin: 'xīn de', viet: 'mới' },
    { zh: '发展计划', pinyin: 'fāzhǎn jìhuà', viet: 'kế hoạch phát triển' },
  ],
  '买': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '想买', pinyin: 'xiǎng mǎi', viet: 'muốn mua' },
    { zh: '一台', pinyin: 'yī tái', viet: 'một chiếc' },
    { zh: '新手机', pinyin: 'xīn shǒujī', viet: 'điện thoại mới' },
    { zh: '但', pinyin: 'dàn', viet: 'nhưng' },
    { zh: '还没决定', pinyin: 'hái méi juédìng', viet: 'chưa quyết định' },
    { zh: '买哪个', pinyin: 'mǎi nǎge', viet: 'mua cái nào' },
    { zh: '牌子', pinyin: 'páizi', viet: 'thương hiệu' },
  ],
  '卖': [
    { zh: '他', pinyin: 'tā', viet: 'anh ấy' },
    { zh: '把', pinyin: 'bǎ', viet: '(giới từ)' },
    { zh: '旧电脑', pinyin: 'jiù diànnǎo', viet: 'máy tính cũ' },
    { zh: '卖掉了', pinyin: 'mài diào le', viet: 'bán đi rồi' },
    { zh: '换了', pinyin: 'huàn le', viet: 'đổi' },
    { zh: '一台', pinyin: 'yī tái', viet: 'một chiếc' },
    { zh: '更好的', pinyin: 'gèng hǎo de', viet: 'tốt hơn' },
    { zh: '新机器', pinyin: 'xīn jīqì', viet: 'máy mới' },
  ],
  '付钱': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '在', pinyin: 'zài', viet: 'ở' },
    { zh: '收银台', pinyin: 'shōuyíntái', viet: 'quầy thu ngân' },
    { zh: '付钱', pinyin: 'fùqián', viet: 'trả tiền' },
    { zh: '的时候', pinyin: 'de shíhou', viet: 'khi' },
    { zh: '发现', pinyin: 'fāxiàn', viet: 'phát hiện' },
    { zh: '钱包', pinyin: 'qiánbāo', viet: 'ví tiền' },
    { zh: '忘在', pinyin: 'wàng zài', viet: 'bỏ quên ở' },
    { zh: '家里了', pinyin: 'jiā lǐ le', viet: 'nhà rồi' },
  ],
  '付款': [
    { zh: '这家店', pinyin: 'zhè jiā diàn', viet: 'cửa hàng này' },
    { zh: '支持', pinyin: 'zhīchí', viet: 'hỗ trợ' },
    { zh: '微信', pinyin: 'Wēixìn', viet: 'WeChat' },
    { zh: '和', pinyin: 'hé', viet: 'và' },
    { zh: '支付宝', pinyin: 'Zhīfùbǎo', viet: 'Alipay' },
    { zh: '付款', pinyin: 'fùkuǎn', viet: 'thanh toán' },
    { zh: '非常方便', pinyin: 'fēicháng fāngbiàn', viet: 'rất tiện lợi' },
  ],
  '收钱': [
    { zh: '老板', pinyin: 'lǎobǎn', viet: 'ông chủ' },
    { zh: '让我', pinyin: 'ràng wǒ', viet: 'nhờ tôi' },
    { zh: '帮他', pinyin: 'bāng tā', viet: 'giúp ông ấy' },
    { zh: '在门口', pinyin: 'zài ménkǒu', viet: 'ở cửa' },
    { zh: '收钱', pinyin: 'shōuqián', viet: 'nhận tiền' },
    { zh: '今天', pinyin: 'jīntiān', viet: 'hôm nay' },
    { zh: '客人', pinyin: 'kèrén', viet: 'khách' },
    { zh: '很多', pinyin: 'hěn duō', viet: 'rất đông' },
  ],
  '找钱': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '付了', pinyin: 'fù le', viet: 'đã trả' },
    { zh: '一百块', pinyin: 'yī bǎi kuài', viet: 'một trăm tệ' },
    { zh: '老板', pinyin: 'lǎobǎn', viet: 'ông chủ' },
    { zh: '找钱', pinyin: 'zhǎoqián', viet: 'trả lại tiền' },
    { zh: '给我', pinyin: 'gěi wǒ', viet: 'cho tôi' },
    { zh: '找了', pinyin: 'zhǎo le', viet: 'trả lại' },
    { zh: '三十五块', pinyin: 'sānshíwǔ kuài', viet: 'ba mươi lăm tệ' },
  ],
  '选': [
    { zh: '这里', pinyin: 'zhèlǐ', viet: 'ở đây' },
    { zh: '颜色', pinyin: 'yánsè', viet: 'màu sắc' },
    { zh: '太多了', pinyin: 'tài duō le', viet: 'quá nhiều' },
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '选了半天', pinyin: 'xuǎn le bàntiān', viet: 'chọn mãi' },
    { zh: '还是', pinyin: 'háishi', viet: 'vẫn' },
    { zh: '不知道', pinyin: 'bù zhīdào', viet: 'không biết' },
    { zh: '选哪个好', pinyin: 'xuǎn nǎge hǎo', viet: 'nên chọn cái nào' },
  ],
  '看': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '先', pinyin: 'xiān', viet: 'trước' },
    { zh: '看了一下', pinyin: 'kàn le yīxià', viet: 'xem qua' },
    { zh: '商品的', pinyin: 'shāngpǐn de', viet: 'của sản phẩm' },
    { zh: '评价', pinyin: 'píngjià', viet: 'đánh giá' },
    { zh: '觉得', pinyin: 'juéde', viet: 'thấy' },
    { zh: '质量不错', pinyin: 'zhìliàng bùcuò', viet: 'chất lượng ổn' },
    { zh: '才下单', pinyin: 'cái xià dān', viet: 'rồi mới đặt hàng' },
  ],
  '比较': [
    { zh: '买东西', pinyin: 'mǎi dōngxi', viet: 'mua đồ' },
    { zh: '之前', pinyin: 'zhīqián', viet: 'trước khi' },
    { zh: '最好', pinyin: 'zuì hǎo', viet: 'tốt nhất' },
    { zh: '多比较', pinyin: 'duō bǐjiào', viet: 'so sánh nhiều' },
    { zh: '几家店', pinyin: 'jǐ jiā diàn', viet: 'vài cửa hàng' },
    { zh: '选', pinyin: 'xuǎn', viet: 'chọn' },
    { zh: '最划算的', pinyin: 'zuì huásuàn de', viet: 'có lợi nhất' },
    { zh: '那个', pinyin: 'nàge', viet: 'cái đó' },
  ],
  '下单': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '刚刚', pinyin: 'gānggāng', viet: 'vừa mới' },
    { zh: '在网上', pinyin: 'zài wǎng shàng', viet: 'trên mạng' },
    { zh: '下单了', pinyin: 'xià dān le', viet: 'đặt hàng rồi' },
    { zh: '选择了', pinyin: 'xuǎnzé le', viet: 'đã chọn' },
    { zh: '最快的', pinyin: 'zuì kuài de', viet: 'nhanh nhất' },
    { zh: '配送方式', pinyin: 'pèisòng fāngshì', viet: 'phương thức giao hàng' },
  ],
  '加入': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '把', pinyin: 'bǎ', viet: '(giới từ)' },
    { zh: '这双鞋', pinyin: 'zhè shuāng xié', viet: 'đôi giày này' },
    { zh: '加入', pinyin: 'jiārù', viet: 'thêm vào' },
    { zh: '购物车', pinyin: 'gòuwùchē', viet: 'giỏ hàng' },
    { zh: '等', pinyin: 'děng', viet: 'đợi' },
    { zh: '发工资了', pinyin: 'fā gōngzī le', viet: 'khi lĩnh lương' },
    { zh: '再买', pinyin: 'zài mǎi', viet: 'rồi mới mua' },
  ],
  '取消': [
    { zh: '我', pinyin: 'wǒ', viet: 'tôi' },
    { zh: '发现', pinyin: 'fāxiàn', viet: 'phát hiện' },
    { zh: '买错了', pinyin: 'mǎi cuò le', viet: 'mua nhầm rồi' },
    { zh: '赶紧', pinyin: 'gǎnjǐn', viet: 'vội' },
    { zh: '联系', pinyin: 'liánxì', viet: 'liên hệ' },
    { zh: '客服', pinyin: 'kèfú', viet: 'bộ phận CSKH' },
    { zh: '取消了', pinyin: 'qǔxiāo le', viet: 'đã hủy' },
    { zh: '订单', pinyin: 'dìngdān', viet: 'đơn hàng' },
  ],
};
